### ISSUE TITLE
"Bot run failed" notification ❌ 

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/Python_Scripts#42]
**Hi Jeremy 👋,**

**Every time I submit a PR to this repository the bots send me this messages/notifications (1 or 2 per issue/pr) (e-mail too):**

![image](https://user-images.githubusercontent.com/124001513/222985640-e0c91618-3d5f-42d3-bbfd-a726c5af4ced.png)

![image](https://user-images.githubusercontent.com/124001513/222985653-8f053f0b-82e3-4d59-8fea-17422b5eb024.png)

_Can you delete it?_

> Hope you fix this and best wishes, 
> Dr-nefardio3058

**Comment by jge162** [comment]
I reviewed the GitHub action for delete_spam and don't see any issues. Might be a false message for you, but works fine for me. Thanks for bringing up the issue nonetheless, I will double check again.

**Comment by jge162** [comment]
I found and patched the issue. It had push: in the on call and should not have. `push` has now been removed.

**Comment by jge162** [comment]
You need to remove  the push from your forked version, also note: I have secrets setup for my email address and email password. So until you create your on secrets it will always fail on your forked version. Hope this helps you.

**Comment by dr-nefardio3058** [comment]
Nice bro good job this was driving me crazy
