### ISSUE TITLE
Obsolete readme buttons

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/Python_Scripts#47]
### Hi Jeremy 👋 ,

**Opening this issue as I saw that these buttons aren't updated in terms of size and numbers and files.**

_Currently there are 57 files, button says 15.
Currently the size of the repository is 339KB, button says 270KB._

Couldn't do a PR because the buttons are hard-coded, they can't be edited.

**Screenshots below:**

![image](https://user-images.githubusercontent.com/124001513/223271348-5da582a2-db5e-4b15-b5f6-5f9da86d61cf.png)

![image](https://user-images.githubusercontent.com/124001513/223271100-43b53f43-5799-49bf-a075-d6aebc3733aa.png)

> See you soon! 🐱

**Comment by dr-nefardio3058** [comment]
@jge162 the bot did not assign "non owner issue to this" issue! Problem resolved!

**Comment by jge162** [comment]
Yes I removed it. I’ll track down the action in a few.

**Comment by jge162** [comment]
I looked at the buttons they seem to be broken. Cause all the information is correct. But the data is not updating.

**Comment by jge162** [comment]
Ok I updated the action to instead of creating a label called `non owner issue` to instead create a label called `new issue.`

**Comment by dr-nefardio3058** [comment]
> Ok I updated the action to instead of creating a label called `non owner issue` to instead create a label called `new issue.`

I'll test it let's see.

**Comment by jge162** [comment]
Ok I double checked and it appears that the badges count only the root items. So nothing in .GitHub is being counted. That appears to be intentional behavior of io shield.

**Comment by jge162** [comment]
![3543C2E0-50F0-4529-8164-46BDA98C9396](https://user-images.githubusercontent.com/31228460/223280530-f15a0be9-2473-456b-b480-76b95a8bcdcb.jpeg)
Seems like it only sees root files.

**Comment by dr-nefardio3058** [comment]
> ![3543C2E0-50F0-4529-8164-46BDA98C9396](https://user-images.githubusercontent.com/31228460/223280530-f15a0be9-2473-456b-b480-76b95a8bcdcb.jpeg) Seems like it only sees root files.

Doesn't see .github? Almost half of the files are there!

**Comment by jge162** [comment]
![A2E56787-FB37-450A-B10F-F6FA9E88014A](https://user-images.githubusercontent.com/31228460/223280825-814f66c6-92b0-4749-a268-04b7c4521bde.jpeg)

I added one additional file to root and now it says 16. So confirmation. It does not count .GitHub files

**Comment by jge162** [comment]
So it is working as intended. Thanks for spotting discrepancy. Have a great day.

**Comment by dr-nefardio3058** [comment]
But we gotta fix the buttons @jge162

**Comment by jge162** [comment]
Button is working as intended I confirmed it. If you find different ones lmk thanks.
